config/routes.rb
Omrails::Application.routes.draw do

  resources :pins

  devise_for :users
get'about' => 'pages#about'

root 'pages#home'

  

end

app/models/pin.rb
class Pin < ActiveRecord::Base	

	validates :description, presence: true
	validates :user_id, presence: true
	validates_attachment :image, presence: true,
							content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']},
							size: {less_than: 5.megabytes }

	belongs_to :user
	has_attached_file :image, styles: {medium: "320x240>"}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, # :recoverable,
         :rememberable, :trackable, :validatable
  validates_presence_of :name

  has_many :pins, :dependent => :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :current_password, :password, :password_confirmation) }
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def action
  	#content
  	#Rules
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  before_action :set_pin, only: [:edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.order("created_at desc")
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
   @pin = Pin.find(params[:id])
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = current_user.pins.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
	<div class="footer">
			<small>
				Find me on twitter <%= link_to "@pqoneil", "http://www.twitter.com/pqoneil"%>
			</small>

		</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
	      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
	     <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	     </a>
	 
	      <!-- Be sure to leave the brand out there if you want it shown -->
	      <%= link_to "One Month Rails", root_path, class: "brand" %> 
	 
	      <!-- Everything you want hidden at 940px or less, place within here -->
	     <div class="nav-collapse collapse ">
			<ul class ="nav">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "About Us", about_path %></li>
			</ul>   

			<ul class ="nav pull-right">
				<%if user_signed_in? %>
				<li><%= link_to "Add +", new_pin_path %>
				<li><%= link_to "Edit Profile", edit_user_registration_path %></li>
				<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
				<% else %>
				<li><%= link_to "Login", new_user_session_path %></li>
				<% end %> 
			</ul>   
		</div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>One Month Rails</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>

	<body>
		<%= render 'layouts/header' %>
		<div class="container">

			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
			<% end %>

		<%= yield %>
		<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>This is the sample app  for <%= link_to "One Month Rail","http://www.onemonthrails.com"%>

</p>

app/views/pages/home.html.erb
<%if user_signed_in? %>

<h1>You're Logged In</h1>

<% else %>

<div class="hero-unit">
	<h1>Welcome to Test App!</h1>
	<p> You've found the home page!

		<%= link_to "One Month Rails", "http://www.onemontrails.com" %> 

	</p>

	<p>
	<%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %>
</div>
<% end %> 

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

  	<%= f.input :image, label: "Upload an image" %>
    <%= f.input :description, as: :text, input_html: { rows: "3" } %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div class="box">
	<%= link_to (image_tag pin.image(:medium)), pin %>
	<p class="description">
		<%= pin.description %>
	</p>
	<p>
			<strong>
				Posted by <%= pin.user.name %>
			</strong>
	</p>	
	<% if current_user == pin.user %>
		<p>
			<%= link_to 'Edit', edit_pin_path(pin) %>
			<%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
		</p>
	<% end %>
</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<div id="pins">
  <%= render @pins %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<%= image_tag @pin.image %>
			<p>
				<%= @pin.description %>
			</p>
			<p>
				<%= @pin.user.name %>
			</p>
			<% if current_user == @pin.user %>
				<%= link_to 'Edit', edit_pin_path(@pin) %> |
			<% end %>
			<%= link_to 'Back', pins_path %>
		</div>
	</div>
</div>